#!/bin/sh
### BEGIN INIT INFO
# Provides:          pmb280
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start BMP280 reader at boot
### END INIT INFO

case "$1" in
  start)
    echo "Starting BME280 Reader"
    /usr/bin/bme280 &
    ;;
  stop)
    echo "Stopping BME280 Reader"
    killall bme280
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/pme280 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

